### ISSUE TITLE
Error line wasabi_mining/ui/main.js:29

### ISSUE THREAD

**Issue by panamera999** [wasabirobby/wasabi_mining#2]
![1ERsYyR](https://user-images.githubusercontent.com/95368610/156227658-97dcc34a-781b-46b0-b407-cd1796ad0d94.png)

Does anyone know what the error may be, i've not changed anything. Resource name is "wasabi_mining" in the server.cfg

**Comment by wasabirobby** [comment]
Fixed with latest version.

Download version 1.1.1 as a remedy.
