### ISSUE TITLE
server.lua:41: attempt to concatenate a nil value (local 'awardItemLabel')

### ISSUE THREAD

**Issue by duckysuck** [wasabirobby/wasabi_mining#3]
[script:wasabi_mining] SCRIPT ERROR: @wasabi_mining/server/server.lua:41: attempt to concatenate a nil value (local 'awardItemLabel')

which links to this;
 TriggerClientEvent('wasabi_mining:notify', source, Language['cantcarry']..' '..awardItemLabel)

**Comment by wasabirobby** [comment]
Should be resolved in latest version
