### ISSUE TITLE
error object is not a string

### ISSUE THREAD

**Issue by Esterze** [wasabirobby/wasabi_mining#5]
[  script:es_extended] SCRIPT ERROR: @es_extended/server/functions.lua:347: attempt to concatenate a nil value (local 'item')
[  script:es_extended] > handler (@wasabi_mining/server/server.lua:23)
[script:wasabi_mining] SCRIPT ERROR: error object is not a string

**Comment by wasabirobby** [comment]
This fixed in latest version. Ensure items within config are present in items of inventory
