### ISSUE TITLE
[Improvment] Migrating to ox_lib skillcheck

### ISSUE THREAD

**Issue by lexinor** [wasabirobby/wasabi_mining#6]
Could you migrate your skillcheck to the ox' ones ?

**Comment by Esterze** [comment]
Probably not, as this repo is abandoned.

**Comment by lexinor** [comment]
> Probably not, as this repo is abandoned.

Why ??

**Comment by wasabirobby** [comment]
Zzeyy must have mistaken this for his own repo since he is deciding it is abandoned.

I will be updating the skill-check, notifications, and other features fairly soon.

**Comment by lexinor** [comment]
> Zzeyy must have mistaken this for his own repo since he is deciding it is abandoned.
> 
> I will be updating the skill-check, notifications, and other features fairly soon.

Hahah that's exactly what I thought, thanks for your answer mate
