### ISSUE TITLE
Object is not a string

### ISSUE THREAD

**Issue by Esterze** [wasabirobby/wasabi_mining#7]
```
[script:wasabi_mining] SCRIPT ERROR: error object is not a string
[  script:es_extended] SCRIPT ERROR: @es_extended/server/functions.lua:347: attempt to concatenate a nil value (local 'item')
[  script:es_extended] > handler (@wasabi_mining/server/server.lua:23)
```

**Comment by wasabirobby** [comment]
Ensure all items are in items of your inventory

**Comment by Esterze** [comment]
They are

**Comment by Esterze** [comment]
I set up the config so it gives only copper, iron and steel
All items are present in my ox inventory
![image](https://user-images.githubusercontent.com/97387354/202570390-4aa19b12-7077-4fc8-8ce0-7e74dd574aa4.png)

**Comment by Esterze** [comment]
But the error is no more in the 2.0 release, case closed, keep the good work up
